import Link from "next/link";
import { Check, Zap, Search, Shield, Globe, ArrowRight, Star } from "lucide-react";

const plans = [
  {
    name: "Starter",
    price: "$29",
    description: "For solo practitioners",
    features: [
      "1 provider",
      "All core pages",
      "SEO engine",
      "Custom domain + SSL",
      "Professional email forwarding",
      "Basic analytics",
    ],
  },
  {
    name: "Professional",
    price: "$59",
    description: "For growing practices",
    popular: true,
    features: [
      "Up to 3 providers",
      "Everything in Starter",
      "Blog & video gallery",
      "Google Search Console",
      "Monthly SEO report",
      "Review aggregation",
      "AI blog posts (2/mo)",
    ],
  },
  {
    name: "Practice",
    price: "$99",
    description: "For established practices",
    features: [
      "Up to 10 providers",
      "Everything in Professional",
      "Built-in form builder (HIPAA)",
      "Advanced analytics",
      "Multiple locations",
      "2-way patient texting",
      "AI blog posts (8/mo)",
    ],
  },
];

const features = [
  {
    icon: Zap,
    title: "Live in 30 Minutes",
    description:
      "Fill out a form, pick your style, and your site is live. No designers, no developers, no weeks of waiting.",
  },
  {
    icon: Search,
    title: "SEO Built In",
    description:
      "Every page is optimized for local search from day one. Structured data, meta tags, and Google Business Profile — automatic.",
  },
  {
    icon: Shield,
    title: "HIPAA-Ready",
    description:
      "Consent forms, intake forms, and patient communication designed with healthcare compliance in mind.",
  },
  {
    icon: Globe,
    title: "Custom Domain & Email",
    description:
      "Your own domain with professional email addresses. dr.smith@yourpractice.com — not yourpractice@gmail.com.",
  },
  {
    icon: Star,
    title: "Reputation Management",
    description:
      "Aggregate reviews from Google and Healthgrades. Request new reviews automatically after appointments.",
  },
  {
    icon: ArrowRight,
    title: "AI-Powered Content",
    description:
      "Blog posts, service descriptions, and social media content generated by AI — you just approve and publish.",
  },
];

const specialties = [
  "OBGYN",
  "Family Medicine",
  "Dermatology",
  "Orthopedics",
  "Pediatrics",
  "Internal Medicine",
  "Medical Spa",
  "Cardiology",
  "Urology",
  "ENT",
];

export default function Home() {
  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-gray-200">
        <nav className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold text-slate-800">
            Santelis<span className="text-teal-600">Health</span>
          </Link>
          <div className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-sm text-gray-600 hover:text-gray-900">
              Features
            </a>
            <a href="#specialties" className="text-sm text-gray-600 hover:text-gray-900">
              Specialties
            </a>
            <a href="#pricing" className="text-sm text-gray-600 hover:text-gray-900">
              Pricing
            </a>
            <Link
              href="/onboard"
              className="bg-teal-600 hover:bg-teal-700 text-white text-sm font-medium px-5 py-2.5 rounded-lg transition-colors"
            >
              Get Started
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero */}
      <section className="py-24 md:py-32">
        <div className="container mx-auto px-4 max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 bg-teal-50 text-teal-700 text-sm font-medium px-4 py-1.5 rounded-full mb-6">
            <Zap className="w-4 h-4" />
            Built by a doctor, for doctors
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-slate-900 mb-6 leading-tight">
            Your practice deserves a{" "}
            <span className="text-teal-600">better website</span>
          </h1>
          <p className="text-xl text-gray-600 mb-10 max-w-2xl mx-auto">
            AI-powered website builder for medical practices. Modern, fast, SEO-optimized —
            live in under 30 minutes. No developers needed.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/onboard"
              className="bg-teal-600 hover:bg-teal-700 text-white font-semibold px-8 py-3.5 rounded-lg transition-colors text-lg inline-flex items-center justify-center gap-2"
            >
              Build Your Site
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              href="/demo/kleins-womens-care"
              className="border-2 border-gray-300 hover:border-teal-600 text-gray-700 hover:text-teal-600 font-semibold px-8 py-3.5 rounded-lg transition-colors text-lg text-center"
            >
              See a Live Example
            </Link>
          </div>
          <p className="text-sm text-gray-500 mt-6">
            No credit card required. Free preview before you commit.
          </p>
        </div>
      </section>

      {/* Social proof bar */}
      <section className="border-y border-gray-200 bg-gray-50 py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-center gap-8 md:gap-16 text-center">
            <div>
              <p className="text-3xl font-bold text-slate-800">97+</p>
              <p className="text-sm text-gray-600">PageSpeed Score</p>
            </div>
            <div>
              <p className="text-3xl font-bold text-slate-800">&lt;30 min</p>
              <p className="text-sm text-gray-600">Time to Live Site</p>
            </div>
            <div>
              <p className="text-3xl font-bold text-slate-800">$0</p>
              <p className="text-sm text-gray-600">Setup Fee</p>
            </div>
            <div>
              <p className="text-3xl font-bold text-slate-800">10</p>
              <p className="text-sm text-gray-600">Specialties Supported</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center text-slate-900 mb-4">
            Everything your practice needs
          </h2>
          <p className="text-center text-gray-600 mb-16 max-w-2xl mx-auto">
            Not just a website — a complete digital presence with SEO, email, reputation management,
            and AI content built in.
          </p>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {features.map((feature) => (
              <div key={feature.title} className="p-6">
                <div className="w-12 h-12 bg-teal-50 rounded-xl flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-teal-600" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">{feature.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Specialties */}
      <section id="specialties" className="py-24 bg-gray-50">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold text-slate-900 mb-4">
            Built for your specialty
          </h2>
          <p className="text-gray-600 mb-12 max-w-2xl mx-auto">
            Not generic templates. Every specialty gets its own curated design, default services,
            credential badges, and SEO keywords.
          </p>
          <div className="flex flex-wrap justify-center gap-3 max-w-3xl mx-auto">
            {specialties.map((specialty) => (
              <span
                key={specialty}
                className="px-5 py-2.5 bg-white border border-gray-200 rounded-full text-sm font-medium text-slate-700 hover:border-teal-600 hover:text-teal-600 transition-colors cursor-default"
              >
                {specialty}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center text-slate-900 mb-16">
            Live in 3 steps
          </h2>
          <div className="grid md:grid-cols-3 gap-12 max-w-4xl mx-auto">
            {[
              {
                step: "1",
                title: "Tell us about your practice",
                description:
                  "Fill out a short form — specialty, services, providers, branding preferences. AI fills in the rest.",
              },
              {
                step: "2",
                title: "Preview your site",
                description:
                  "See your fully-built website instantly. Edit anything you want before going live.",
              },
              {
                step: "3",
                title: "Go live",
                description:
                  "Pick your domain, choose a plan, and your site is live with SEO, email, and analytics — all automatic.",
              },
            ].map((item) => (
              <div key={item.step} className="text-center">
                <div className="w-12 h-12 bg-teal-600 text-white rounded-full flex items-center justify-center text-lg font-bold mx-auto mb-4">
                  {item.step}
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">{item.title}</h3>
                <p className="text-gray-600 text-sm">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 bg-gray-50">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center text-slate-900 mb-4">
            Simple, transparent pricing
          </h2>
          <p className="text-center text-gray-600 mb-16 max-w-2xl mx-auto">
            No setup fees. No contracts. Cancel anytime. Every plan includes a custom domain and SSL.
          </p>
          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {plans.map((plan) => (
              <div
                key={plan.name}
                className={`rounded-2xl p-8 ${
                  plan.popular
                    ? "bg-teal-600 text-white ring-2 ring-teal-600 scale-105"
                    : "bg-white border border-gray-200"
                }`}
              >
                {plan.popular && (
                  <span className="inline-block bg-white text-teal-600 text-xs font-bold px-3 py-1 rounded-full mb-4">
                    Most Popular
                  </span>
                )}
                <h3
                  className={`text-xl font-bold mb-1 ${plan.popular ? "text-white" : "text-slate-900"}`}
                >
                  {plan.name}
                </h3>
                <p className={`text-sm mb-6 ${plan.popular ? "text-teal-100" : "text-gray-600"}`}>
                  {plan.description}
                </p>
                <div className="flex items-baseline gap-1 mb-8">
                  <span className={`text-4xl font-bold ${plan.popular ? "text-white" : "text-slate-900"}`}>
                    {plan.price}
                  </span>
                  <span className={`text-sm ${plan.popular ? "text-teal-100" : "text-gray-500"}`}>
                    /mo
                  </span>
                </div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map((feature) => (
                    <li key={feature} className="flex items-start gap-2">
                      <Check
                        className={`w-5 h-5 mt-0.5 flex-shrink-0 ${
                          plan.popular ? "text-teal-200" : "text-teal-600"
                        }`}
                      />
                      <span className={`text-sm ${plan.popular ? "text-white" : "text-gray-700"}`}>
                        {feature}
                      </span>
                    </li>
                  ))}
                </ul>
                <Link
                  href="/onboard"
                  className={`block text-center font-semibold py-3 rounded-lg transition-colors ${
                    plan.popular
                      ? "bg-white text-teal-600 hover:bg-teal-50"
                      : "bg-teal-600 text-white hover:bg-teal-700"
                  }`}
                >
                  Get Started
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="container mx-auto px-4 max-w-3xl text-center">
          <h2 className="text-3xl font-bold text-slate-900 mb-4">
            Stop overpaying for a website you&apos;re not proud of
          </h2>
          <p className="text-gray-600 mb-10 text-lg">
            Most doctor websites cost $200-500/mo and look like they were built in 2015.
            Yours doesn&apos;t have to.
          </p>
          <Link
            href="/onboard"
            className="bg-teal-600 hover:bg-teal-700 text-white font-semibold px-8 py-3.5 rounded-lg transition-colors text-lg inline-flex items-center gap-2"
          >
            Build Your Site Free
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-12 bg-slate-900 text-gray-400">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm">
              &copy; {new Date().getFullYear()} Santelis Health. All rights reserved.
            </p>
            <p className="text-sm">
              Built by{" "}
              <a href="https://geffreyklein.com" className="text-teal-400 hover:text-teal-300">
                Geffrey Klein, MD
              </a>
            </p>
          </div>
        </div>
      </footer>
    </main>
  );
}
